name: Python package tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Install library (root pyproject)
        run: |
          pip install . --index-url https://download.pytorch.org/whl/cpu
      - name: Run library tests
        run: |
          pytest programs/demos/nn_lib -q
      - name: Run root tests
        run: |
          pytest tests -q
