name: Python package tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Install library (root pyproject)
        run: |
          # Install torch/torchvision from the PyTorch CPU index first so the rest of the deps (e.g. matplotlib)
          # are still resolved from PyPI (previously we overrode the index and matplotlib was missing there)
          pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
          # Now install our package from the default PyPI index
          pip install .
      - name: Run library tests
        run: |
          pytest programs/demos/nn_lib -q
      - name: Run root tests
        run: |
          pytest tests -q
